### ISSUE TITLE
Missing librairies

### ISSUE THREAD

**Issue by JohnQ86** [rsrawley/spaControl#5]
Hi,

The librairies folder seems to be a shortcut to « spaControl » master page. Is it normal? Node throws me an error for missing gmail.js file.

Thanks

**Comment by rsrawley** [comment]
Hello !

Thanks for kicking my butt into gear! The "libraries" folder contains only one script, gmail.js that I always omitted during pushes as it contained my login credentials for gmail.  This is no longer the case, as I have moved the two files that contain credentials (one for gmail, spa.credentials, and one for phone numbers, spa.addressbook) up one level from the spa directory (hence the ${path}/../ ) to make sure they were not pushed.  However, I never changed the omission of gmail.js during git pushes. On top of that, the program does not fail gracefully as you don't really need either to work (they are used to send texts to my cell phone when the spa has attained the desired temperature).  It had been in the back of my mind, but now I will finally get to it!

Thanks for the "push"!!!

**Comment by rsrawley** [comment]
Got rid of libraries and made made "extras" available as options.  They can be disabled as people see fit (the web site will respond to these options being disabled as well).  Also, code will continue if loading of files fails for certain options.  This should make it easy for anybody to download the code and start using right away, assuming you have the required npm packages installed.
